version: '3.8'

services:
  app:
    build:
      context: ./backend
    container_name: cakephp_app
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: my_hometown
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

  frontend:
    image: node:18
    container_name: react_app
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"