version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    networks:
      - app-network

  node:
    image: node:18
    container_name: react_app
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - app-network
    command: npm start

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: my_hometown_guide
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./backend:/var/www/html
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge